Weather APP
rachaouldbabaali/react-capstone pull request #2
Opened 2023-07-06 20:46 UTC by rachaouldbabaali

In this PR, I have :

 

- [x] Developed reusable components including Navbar, Details, City, and Heading.

- [x] Implemented a Home page that has a search bar with autosuggestion.

- [x] Developed a cities page that dynamically loads a list of cities based on the user's selected country.

- [x] Implemented a Details page that fetches weather data from an API and displays it to the user.

- [x] Styled the entire application to meet the design need based on the Ballhead App design idea by Nelson Sakwa on Behance.

link to the presentation [vidéo](https://www.loom.com/share/09fd4aa765cd4956961fadd273aa970f)

2023-07-06 22:34 UTC, omarsalem7 requested changes
Hi @rachaouldbabaali 😊, 

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![you-are-near](https://media.giphy.com/media/j7vckgz15cAYmxatzB/giphy.gif)

## Highlights
- App created using react app ✔️
- Use react-router properly✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-06 22:34 UTC, omarsalem7 commented on README.md
> +
- [ ] Kindly consider giving appropriate credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

2023-07-06 22:34 UTC, omarsalem7 commented on README.md
> +[N/A]
- [ ] Kindly consider deploying the application using Render, Netlify or GitHub Pages.

2023-07-06 22:45 UTC, rachaouldbabaali commented
Thank you @omarsalem7 😃

2023-07-06 23:03 UTC, Ismailco approved these changes
### Hi @rachaouldbabaali, 

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![cr-approve](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)

## Highlights

✔️ Follow design guidelines
✔️ No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2023-07-07 09:49 UTC, rachaouldbabaali commented
thank you @Ismailco

2023-07-07 09:49 UTC, merged